[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "grow"]
set = true

[templates.ignis]
input_path = './templates/colors.scss'
output_path = '~/.config/ignis/colors.scss'

[templates.hypr]
input_path = './templates/colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.kitty]
input_path = './templates/kitty.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.waybar]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.wofi]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/wofi/colors.css'

[templates.dock]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/nwg-dock-hyprland/colors.css'

[templates.swaync]
input_path = './templates/swaync.css'
output_path = '~/.config/swaync/colors.css'

# [templates.gtk4]
# input_path = './templates/gtk-colors.css'
# output_path = '~/.config/gtk-4.0/colors.css'

# [templates.qt5ct]
# input_path = './templates/qt-colors.conf'
# output_path = '~/.config/qt5ct/colors/matugen.conf'

# [templates.qt6ct]
# input_path = './templates/qt-colors.conf'
# output_path = '~/.config/qt6ct/colors/matugen.conf'

# [templates.vscode] # hyprluna
# input_path = "~/.config/matugen/templates/hyprlunavsc.json"
# output_path = "~/.vscode/extensions/hyprluna.hyprluna-theme-1.0.2/themes/hyprluna.json"
